CONTENT   := quiz-generator/bin/content
DECKS_SRC := decks
DECKS_OUT := assets/decks
# Spark, on the local network. SPARK_LLM serves text models only (translate and
# the tune loop's validator/builder); every image is generated by ComfyUI on
# SPARK_IMG — there is no other image backend.
SPARK_LLM ?= http://spark-99bb:8080
SPARK_IMG ?= http://spark-99bb:8188
WORKERS   ?= 5

# Models for the restyle passes (names as they appear in ComfyUI's model folders).
# Empty means "use the tool's built-in default", which tracks what Spark has
# installed; set these only to try a different checkpoint.
PONY_CKPT  ?=
ILLU_CKPT  ?=
CONTROLNET ?=

# Models for the iterative image-tuning loop (OpenAI-compatible on $(SPARK_LLM)).
VALIDATOR_MODEL := validator  # vision model that scores generated images
BUILDER_MODEL   := builder    # instruct model that rewrites prompts
TUNE_ITERS      := 4
TUNE_SCORE      := 8

# ── build tool ───────────────────────────────────────────────────────────────

.PHONY: build-tool
build-tool:
	cd quiz-generator && go build -o bin/content ./cmd/content

$(CONTENT): build-tool

# ── lint / build assets ───────────────────────────────────────────────────────

.PHONY: lint
lint: $(CONTENT)
	$(CONTENT) lint -decks $(DECKS_SRC)

.PHONY: lint-strict
lint-strict: $(CONTENT)
	$(CONTENT) lint -decks $(DECKS_SRC) -strict -images

# WEBP_BUILD_FLAG must be here too, not only in `ship`: deck.json's image names
# have to match what publish actually wrote, and a bare `make build` is the
# easier of the two paths to reach by accident.
.PHONY: build
build: $(CONTENT)
	$(CONTENT) build -decks $(DECKS_SRC) -out $(DECKS_OUT) $(WEBP_BUILD_FLAG)

# ── translations ──────────────────────────────────────────────────────────────
# Translate all missing languages for all decks (or pass DECK=animals-sea).

.PHONY: translate
translate: $(CONTENT)
	$(CONTENT) translate -decks $(DECKS_SRC) $(if $(DECK),-deck $(DECK)) \
	  -url $(SPARK_LLM) -workers $(WORKERS)

.PHONY: translate-force
translate-force: $(CONTENT)
	$(CONTENT) translate -decks $(DECKS_SRC) $(if $(DECK),-deck $(DECK)) \
	  -url $(SPARK_LLM) -workers $(WORKERS) -force

# ── images ────────────────────────────────────────────────────────────────────
# Generate missing images for all decks (or pass DECK=animals-sea STYLE=pony-cartoon).
#
# RESTYLE_FLAGS are only read by the img2img restyle styles (pony-* / illustrious-*);
# text-to-image styles ignore them, so they can be passed to every images run.

RESTYLE_FLAGS = $(if $(PONY_CKPT),-pony-checkpoint $(PONY_CKPT)) \
                $(if $(ILLU_CKPT),-illustrious-checkpoint $(ILLU_CKPT)) \
                $(if $(CONTROLNET),-controlnet $(CONTROLNET)) \
                $(if $(DENOISE),-denoise $(DENOISE)) \
                $(if $(CONTROL_STRENGTH),-control-strength $(CONTROL_STRENGTH))

.PHONY: images
images: $(CONTENT)
	$(CONTENT) images -decks $(DECKS_SRC) $(if $(DECK),-deck $(DECK)) \
	  $(if $(STYLE),-style $(STYLE)) \
	  -url $(SPARK_IMG) -workers 2 $(RESTYLE_FLAGS) $(if $(FORCE),-force)

.PHONY: images-force
images-force: $(CONTENT)
	$(CONTENT) images -decks $(DECKS_SRC) $(if $(DECK),-deck $(DECK)) \
	  $(if $(STYLE),-style $(STYLE)) \
	  -url $(SPARK_IMG) -workers 2 $(RESTYLE_FLAGS) -force

# ── restyle: flux base → Pony watercolor / oil (img2img) ──────────────────────
# Repaints each card's photo image through Pony SDXL in a paint medium,
# preserving the composition (ComfyUI img2img: LoadImage → VAEEncode → KSampler).
# Inspired by Kiran's flux2pony pass. The photo base images must exist first:
#   make images DECK=animals-sea STYLE=photo
# Then, writing to images/pony-watercolor/ and images/pony-oil/:
#   make watercolor DECK=animals-sea
#   make oil        DECK=animals-sea
# Pass FORCE=1 to overwrite existing output. The Pony checkpoint defaults inside
# the tool; override with PONY_CKPT=<name>. Tune the style-vs-subject balance with
# DENOISE=<0..1> (higher = freer repaint, more style; lower = closer to the base).
# For a structure-locked repaint that survives a much higher denoise, see the
# Illustrious ControlNet targets below.

# The Pony media have no shorthand target: `watercolor` now names the
# Illustrious preset we actually ship. Reach the Pony ones explicitly:
#   make restyle DECK=animals-sea STYLE=pony-watercolor
#   make restyle DECK=animals-sea STYLE=pony-oil

# ── restyle: flux base → Illustrious art styles (ControlNet img2img) ──────────
# Illustrious knows far more art styles than Pony but far fewer real-world
# objects — it cannot draw an ant. So it never generates from text: it repaints
# the photo base, with a Canny ControlNet pinning the subject's shape
# (LoadImage → Canny → ControlNetApplyAdvanced → KSampler). The structure lock is
# what lets denoise run at 0.75-0.85 so the style actually takes; plain img2img
# would dissolve the subject first. The photo base must exist:
#   make images DECK=animals-insects STYLE=photo
# Then, writing to images/illustrious-<style>/:
#   make anime     DECK=animals-insects
#   make storybook DECK=animals-insects
#   make flat      DECK=animals-insects
#   make ukiyoe    DECK=animals-insects
# FORCE=1 overwrites. Pick models with ILLU_CKPT=<name> CONTROLNET=<name>.
# Balance style vs. subject with DENOISE=<0..1> (higher = more style) and
# CONTROL_STRENGTH=<0..1+> (higher = stricter adherence to the base anatomy).

# ── the three illustrated styles we ship ─────────────────────────────────────
# Every deck ships `photo` plus exactly one of these (see each deck.yaml).

.PHONY: ink
ink: $(CONTENT)
	$(CONTENT) images -decks $(DECKS_SRC) $(if $(DECK),-deck $(DECK)) \
	  -style ink -url $(SPARK_IMG) -workers 2 \
	  $(RESTYLE_FLAGS) $(if $(FORCE),-force)

.PHONY: pastel
pastel: $(CONTENT)
	$(CONTENT) images -decks $(DECKS_SRC) $(if $(DECK),-deck $(DECK)) \
	  -style pastel -url $(SPARK_IMG) -workers 2 \
	  $(RESTYLE_FLAGS) $(if $(FORCE),-force)

.PHONY: watercolor
watercolor: $(CONTENT)
	$(CONTENT) images -decks $(DECKS_SRC) $(if $(DECK),-deck $(DECK)) \
	  -style watercolor -url $(SPARK_IMG) -workers 2 \
	  $(RESTYLE_FLAGS) $(if $(FORCE),-force)

.PHONY: anime
anime: $(CONTENT)
	$(CONTENT) images -decks $(DECKS_SRC) $(if $(DECK),-deck $(DECK)) \
	  -style illustrious-anime -url $(SPARK_IMG) -workers 2 \
	  $(RESTYLE_FLAGS) $(if $(FORCE),-force)

.PHONY: storybook
storybook: $(CONTENT)
	$(CONTENT) images -decks $(DECKS_SRC) $(if $(DECK),-deck $(DECK)) \
	  -style illustrious-storybook -url $(SPARK_IMG) -workers 2 \
	  $(RESTYLE_FLAGS) $(if $(FORCE),-force)

.PHONY: flat
flat: $(CONTENT)
	$(CONTENT) images -decks $(DECKS_SRC) $(if $(DECK),-deck $(DECK)) \
	  -style illustrious-flat -url $(SPARK_IMG) -workers 2 \
	  $(RESTYLE_FLAGS) $(if $(FORCE),-force)

.PHONY: ukiyoe
ukiyoe: $(CONTENT)
	$(CONTENT) images -decks $(DECKS_SRC) $(if $(DECK),-deck $(DECK)) \
	  -style illustrious-ukiyoe -url $(SPARK_IMG) -workers 2 \
	  $(RESTYLE_FLAGS) $(if $(FORCE),-force)

# The remaining artist presets (illustrious-oil, -mucha, -vangogh, pony-*) have
# no shorthand target — there are too many to keep naming. Use `restyle`:
#   make restyle DECK=animals-insects STYLE=illustrious-vangogh
# It works for every style, including the four above.
.PHONY: restyle
restyle: $(CONTENT)
	@test -n "$(STYLE)" || (echo "usage: make restyle DECK=<slug> STYLE=<style>"; exit 1)
	$(CONTENT) images -decks $(DECKS_SRC) $(if $(DECK),-deck $(DECK)) \
	  -style $(STYLE) -url $(SPARK_IMG) -workers 2 \
	  $(RESTYLE_FLAGS) $(if $(FORCE),-force)

# Print every style the pipeline knows.
.PHONY: styles
styles: $(CONTENT)
	@$(CONTENT) styles

# ── publish / ship ────────────────────────────────────────────────────────────
# `ship` is the only correct order, because the three steps depend on each other:
#   1. publish images  → previews land in assets/, full sets in docs/
#   2. build           → reads those trees, records styleAvailability per style
#   3. publish json    → copies the freshly built deck.json to docs/
# Running build before step 1 would mark the new styles undeliverable and the
# store would hide them. Pass DECK=<slug> to ship one deck.

# Published images are WebP: the PNGs in decks/ are lossless masters, but at
# ~1.1 MB each the catalogue does not fit under the GitHub Pages limit. q85 is
# a ~94% saving with no visible loss. Set WEBP_QUALITY=0 to publish raw PNGs.
WEBP_QUALITY ?= 85
WEBP_BUILD_FLAG = $(if $(filter-out 0,$(WEBP_QUALITY)),-webp)

.PHONY: publish
publish: $(CONTENT)
	$(CONTENT) publish -decks $(DECKS_SRC) $(if $(DECK),-deck $(DECK)) $(if $(STYLE),-style $(STYLE)) \
	  -webp-quality $(WEBP_QUALITY)

.PHONY: ship
ship: $(CONTENT)
	$(CONTENT) publish -decks $(DECKS_SRC) $(if $(DECK),-deck $(DECK)) -what images -webp-quality $(WEBP_QUALITY)
	$(CONTENT) build   -decks $(DECKS_SRC) -out $(DECKS_OUT) $(WEBP_BUILD_FLAG)
	$(CONTENT) publish -decks $(DECKS_SRC) $(if $(DECK),-deck $(DECK)) -what json
	@echo
	@echo "shipped. remember: new preview folders need a pubspec.yaml assets entry."

# ── tune (iterative image tuning) ──────────────────────────────────────────────
# Generate → validate (VL model) → refine prompt (instruct model) → loop, per card.
# Saves the final image, the winning prompt (decks/<slug>/tuned/<style>.yaml) and a
# transcript of the LLM conversation (decks/<slug>/tuned/logs/).
# Usage: make tune DECK=animals-sea STYLE=pony-cartoon

.PHONY: tune
tune: $(CONTENT)
	$(CONTENT) images -decks $(DECKS_SRC) $(if $(DECK),-deck $(DECK)) \
	  $(if $(STYLE),-style $(STYLE)) \
	  -url $(SPARK_IMG) -workers 2 -force \
	  -tune -max-iters $(TUNE_ITERS) -score-threshold $(TUNE_SCORE) \
	  -llm-url $(SPARK_LLM) \
	  -validator-model $(VALIDATOR_MODEL) -builder-model $(BUILDER_MODEL)

# ── prompts (debug) ───────────────────────────────────────────────────────────

.PHONY: prompts
prompts: $(CONTENT)
	$(CONTENT) prompts -decks $(DECKS_SRC) $(if $(DECK),-deck $(DECK)) \
	  $(if $(STYLE),-style $(STYLE))

# ── full pipeline for a new deck ─────────────────────────────────────────────
# Usage: make new-deck DECK=animals-sea STYLE=pony-cartoon

.PHONY: new-deck
new-deck: translate images build
	@echo "done: $(DECK) translated + images generated + assets built"

# ── flutter ───────────────────────────────────────────────────────────────────

.PHONY: run
run: build
	flutter run

.PHONY: run-macos
run-macos: build
	flutter run -d macos

.PHONY: analyze
analyze:
	flutter analyze

# ── app screenshots ──────────────────────────────────────────────────────────
# Every screen with UI chrome, once per UI language, on a booted iOS simulator.
# App Review rejected 2.2.2 for mixed languages on one screen; look at these
# before uploading a build. Output: build/screenshots/<lang>_<n>_<screen>.png
# (boot the simulator first: `open -a Simulator`).

SIM ?= iPhone 17 Pro Max

.PHONY: screenshots
screenshots:
	flutter drive \
	  --driver=test_driver/integration_test.dart \
	  --target=integration_test/l10n_screenshots_test.dart \
	  -d "$(SIM)"
