#!/usr/bin/env python3
"""Redraw the language map from the languages the app actually ships.

    python3 tools/world_map.py

Reads the shipped language set out of a built deck (`assets/decks/*.json`),
then rewrites both halves of the map so neither can drift from it:

  docs/world-map-languages.svg  the static map on the landing page
  docs/world-map.html           the interactive one (its LANG_TIER table)

A country counts as supported when at least one language spoken there is one
we ship. That is a yes/no question, which is why the map has two colours; it
used to carry a three-tier "translation quality" scale, and the leftovers of it
were still on the map long after the legend had been reduced to two states.

Country-to-language data lives in the interactive map (`const DATA`) and is not
regenerated here — it describes the world, not our product.
"""
import json
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
SVG = ROOT / "docs" / "world-map-languages.svg"
HTML = ROOT / "docs" / "world-map.html"
DECKS = ROOT / "assets" / "decks"

SUPPORTED_FILL = "#34d399"
UNCOVERED_FILL = "#2a2a38"  # the legend's "Not covered" swatch


def shipped_languages():
    """Base codes the app ships, from a built deck's title map."""
    deck = next(iter(sorted(DECKS.glob("*.json"))), None)
    if deck is None:
        raise SystemExit(f"no built decks in {DECKS}; run `make build` first")
    langs = json.loads(deck.read_text())["titles"].keys()
    return {code.split("-")[0] for code in langs}


def country_data():
    """`const DATA` from the interactive map: country → [[lang, pct, tier], …]."""
    html = HTML.read_text()
    start = html.index("const DATA = ") + len("const DATA = ")
    return json.loads(html[start:html.index(";\n", start)])


def supported_countries(data, langs):
    return {
        cc for cc, rows in data.items()
        if any(code.split("_")[0].split("-")[0] in langs for code, *_ in rows)
    }


def rewrite_svg(supported, langs):
    svg = SVG.read_text()

    def paint(m):
        # ids like "cy-n" and "so-land" are pieces of one country.
        cc = m.group("id").split("-")[0]
        ok = cc in supported
        return (f'<path id="{m.group("id")}" class="{"q-supported" if ok else "q-none"}"'
                f'{m.group("mid")}fill="{SUPPORTED_FILL if ok else UNCOVERED_FILL}"')

    svg, n = re.subn(
        r'<path id="(?P<id>[a-z-]+)" class="q-[a-z]+"(?P<mid>.*?)fill="[^"]*"',
        paint, svg, flags=re.S)

    svg = re.sub(
        r"<!-- Country language support.*?-->",
        "<!-- Country language support (ISO-3166-1 alpha-2). A country is\n"
        "     'supported' if at least one language spoken there is one of the\n"
        f"     {len(langs)} languages the app ships; otherwise 'not covered'.\n"
        "     Generated by tools/world_map.py — do not hand-edit.\n"
        f"     supported: {' '.join(sorted(supported))} -->",
        svg, flags=re.S)

    SVG.write_text(svg)
    return n


def rewrite_html(langs):
    html = HTML.read_text()
    table = {code: "high" for code in sorted(langs)}
    html = re.sub(r"const LANG_TIER = \{.*?\};",
                  "const LANG_TIER = " + json.dumps(table, separators=(",", ":")) + ";",
                  html, count=1, flags=re.S)
    HTML.write_text(html)


def main():
    langs = shipped_languages()
    data = country_data()
    supported = supported_countries(data, langs)

    painted = rewrite_svg(supported, langs)
    rewrite_html(langs)

    print(f"languages shipped : {len(langs)}  {' '.join(sorted(langs))}")
    print(f"countries covered : {len(supported)} of {len(data)}")
    print(f"svg paths painted : {painted}")


if __name__ == "__main__":
    main()
